#pragma once

enum TextureNames {
TEXTURE_GRASS0,
TEXTURE_HEALTH,
TEXTURE_PLANT1,
TEXTURE_SHADOW,
TEXTURE_STONE,
TEXTURE_WATER,
TEXTURE_KITCHENTILE,
TEXTURE_INTROSIGN,
TEXTURE_INTEROSIGN2,
TEXTURE_EYE1,
TEXTURE_EYEBROW1,
TEXTURE_MOUTH1,
TEXTURE_SHIRT,
TEXTURE_TROUSERS,
TEXTURE_STONEFLOOR4,
TEXTURE_MOUNTAINSIDEBOTTOM,
TEXTURE_PLEASE,
};

enum SpriteNames {
SPRITE_NONE,
SPRITE_BODY,
SPRITE_EYES1,
SPRITE_EYES2,
SPRITE_MOUTH1,
SPRITE_MOUTH2,
SPRITE_MOUTH3,
};