#pragma once

#include "global.h"

#include "../src/assets.h"

const MaterialInfo gMaterialIDs[] = {
    {TEXTURE_GRASS0, TEXTURE_GRASS1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_MULTITEX_SHADE, COLFLAG_SOUND_DIRT | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_GRASS | FLOORDEC_PEBBLES, 0, 0, 3, 3, 0, 0, 0, 0}, // grass0
    {TEXTURE_HEALTH, -1, MAT_XLU | MAT_FOG | MAT_DEPTH_READ | MAT_DECAL, CC_TEX_SHADE, COLFLAG_GRIP(4) | COLFLAG_INTANGIBLE, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // health
    {TEXTURE_PLANT1, -1, MAT_CUTOUT | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // plant1
    {TEXTURE_SHADOW, -1, MAT_XLU | MAT_FOG | MAT_DEPTH_READ | MAT_DECAL, CC_TEX_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // shadow
    {TEXTURE_ROCKSIDE3, TEXTURE_ROCKSIDE4, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_MULTITEX_SHADE, COLFLAG_SOUND_STONE | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_PEBBLES, 1, 1, 0, 0, 0, 0, 0, 0}, // stone
    {TEXTURE_WATER, TEXTURE_WATER, MAT_XLU | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_INTER | MAT_BACKFACE, CC_MULTITEX_WATER, COLFLAG_SOUND_WATER | COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 1, 1, 2, 0, 2, 2}, // water
    {TEXTURE_KITCHENTILE, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_TILE | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // kitchentile
    {TEXTURE_INTROSIGN, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // introsign
    {TEXTURE_INTROSIGN2, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // introsign2
    {TEXTURE_EYE1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // eye1
    {TEXTURE_EYEBROW1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // eyebrow1
    {TEXTURE_MOUTH1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // mouth1
    {TEXTURE_SHIRT, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // shirt
    {TEXTURE_TROUSERS, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // trousers
    {TEXTURE_ROCKSURFACE4, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_TEX_SHADE, COLFLAG_SOUND_STONE | COLFLAG_GRIP(8), FLOORDEC_PEBBLES, 0, 0, 0, 0, 0, 0, 0, 0}, // rocksurface4
    {TEXTURE_MOUNTAINSIDEBOTTOM, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_SOUND_STONE | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_PEBBLES, 0, 0, 0, 0, 0, 0, 0, 0}, // mountainsidebottom
    {-1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_SHADE_PRIM, COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // flatprim
    {TEXTURE_LOGWALL, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // logwall
    {TEXTURE_RAILING, -1, MAT_CUTOUT | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_BACKFACE, CC_TEX_SHADE, COLFLAG_SOUND_METAL | COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // railing
    {TEXTURE_CRATE, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // crate
    {-1, -1, MAT_XLU | MAT_LIGHTING | MAT_DEPTH_READ | MAT_VTXCOL, CC_SHADE_PRIM, COLFLAG_SOUND_GLASS | COLFLAG_GRIP(1), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // flatprim_xlu
    {TEXTURE_GRASS0, TEXTURE_GRASS1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_MULTITEX_SHADE, COLFLAG_SOUND_DIRT | COLFLAG_GRIP(8) | COLFLAG_INTANGIBLE | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 3, 3, 0, 0, 0, 0}, // grass0_nzb
    {TEXTURE_BODY1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // body1
    {TEXTURE_EYE1_B, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // eye1_b
    {TEXTURE_FLIPBOOKTEST, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // flipbooktest
    {TEXTURE_ENVMAP, -1, MAT_FOG | MAT_ENVMAP | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_GLASS | COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // reflection
    {TEXTURE_DUST_CLOUDS, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustclouds
    {TEXTURE_DUST_MAT0, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat0
    {TEXTURE_DUST_MAT1, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat1
    {TEXTURE_DUST_MAT2, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat2
    {TEXTURE_DUST_MAT3, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat3
    {TEXTURE_DUST_MAT5, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat5
    {TEXTURE_DUST_MAT6, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat6
    {TEXTURE_DUST_MAT7, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat7
    {TEXTURE_DUST_MAT8, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat8
    {TEXTURE_DUST_MAT9, -1, MAT_CUTOUT | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_DECAL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat9
    {TEXTURE_DUST_MAT10, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat10
    {TEXTURE_DUST_MAT11, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat11
    {TEXTURE_DUST_MAT12, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat12
    {TEXTURE_DUST_MAT13, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat13
    {TEXTURE_DUST_MAT14, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat14
    {TEXTURE_DUST_MAT15, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat15
    {TEXTURE_DUST_MAT16, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat16
    {TEXTURE_DUST_MAT17, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat17
    {TEXTURE_DUST_MAT18, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat18
    {TEXTURE_DUST_MAT19, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat19
    {TEXTURE_DUST_MAT20, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat20
    {TEXTURE_DUST_MAT21, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat21
    {TEXTURE_DUST_MAT22, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat22
    {TEXTURE_DUST_MAT23, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat23
    {TEXTURE_DUST_MAT24, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat24
    {TEXTURE_DUST_MAT25, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat25
    {TEXTURE_DUST_MAT26, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat26
    {TEXTURE_DUST_MAT27, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat27
    {TEXTURE_DUST_MAT28, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat28
    {TEXTURE_DUST_MAT29, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat29
    {TEXTURE_DUST_MAT30, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat30
    {TEXTURE_DUST_MAT31, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat31
    {TEXTURE_DUST_MAT32, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat32
    {TEXTURE_DUST_MAT33, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // dustmat33
};