#pragma once

#include "global.h"

#include "../src/assets.h"

const MaterialInfo gMaterialIDs[] = {
    {TEXTURE_GRASS0, TEXTURE_GRASS1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_MULTITEX_SHADE, COLFLAG_SOUND_DIRT | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_GRASS | FLOORDEC_PEBBLES, 0, 0, 3, 3, 0, 0, 0, 0}, // grass0
    {TEXTURE_HEALTH, -1, MAT_XLU | MAT_FOG | MAT_DEPTH_READ | MAT_DECAL, CC_TEX_SHADE, COLFLAG_GRIP(4) | COLFLAG_INTANGIBLE, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // health
    {TEXTURE_PLANT1, -1, MAT_CUTOUT | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_INVISIBLE, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // plant1
    {TEXTURE_SHADOW, -1, MAT_XLU | MAT_FOG | MAT_DEPTH_READ | MAT_DECAL, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // shadow
    {TEXTURE_ROCKSIDE3, TEXTURE_ROCKSIDE4, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_MULTITEX_SHADE, COLFLAG_SOUND_STONE | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_PEBBLES, 1, 1, 0, 0, 0, 0, 0, 0}, // stone
    {TEXTURE_WATER, TEXTURE_WATER, MAT_XLU | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_INTER | MAT_BACKFACE, CC_MULTITEX_WATER, COLFLAG_SOUND_WATER | COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 1, 1, 2, 0, 2, 2}, // water
    {TEXTURE_KITCHENTILE, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_TILE | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // kitchentile
    {TEXTURE_INTROSIGN, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // introsign
    {TEXTURE_INTROSIGN2, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // introsign2
    {TEXTURE_EYE1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // eye1
    {TEXTURE_EYEBROW1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // eyebrow1
    {TEXTURE_MOUTH1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // mouth1
    {TEXTURE_SHIRT, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // shirt
    {TEXTURE_TROUSERS, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_TEX_SHADE, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // trousers
    {TEXTURE_ROCKSURFACE4, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_TEX_SHADE, COLFLAG_SOUND_STONE | COLFLAG_GRIP(8), FLOORDEC_PEBBLES, 0, 0, 0, 0, 0, 0, 0, 0}, // rocksurface4
    {TEXTURE_MOUNTAINSIDEBOTTOM, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_CI, CC_TEX_SHADE, COLFLAG_SOUND_STONE | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_PEBBLES, 0, 0, 0, 0, 0, 0, 0, 0}, // mountainsidebottom
    {-1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_SHADE_PRIM, COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // flatprim
    {TEXTURE_LOGWALL, -1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // logwall
    {TEXTURE_RAILING, -1, MAT_CUTOUT | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL | MAT_BACKFACE | MAT_INVISIBLE, CC_TEX_SHADE, COLFLAG_SOUND_METAL | COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // railing
    {TEXTURE_CRATE, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_TEX_SHADE, COLFLAG_SOUND_WOOD | COLFLAG_GRIP(8) | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // crate
    {-1, -1, MAT_XLU | MAT_LIGHTING | MAT_DEPTH_READ | MAT_VTXCOL, CC_SHADE_PRIM, COLFLAG_SOUND_GLASS | COLFLAG_GRIP(1), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // flatprim_xlu
    {TEXTURE_GRASS0, TEXTURE_GRASS1, MAT_FOG | MAT_DEPTH_READ | MAT_VTXCOL, CC_MULTITEX_SHADE, COLFLAG_SOUND_DIRT | COLFLAG_GRIP(8) | COLFLAG_INTANGIBLE | COLFLAG_SHADOW, FLOORDEC_NONE, 0, 0, 3, 3, 0, 0, 0, 0}, // grass0_nzb
    {TEXTURE_BODY1, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // body1
    {TEXTURE_EYE1_B, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // eye1_b
    {TEXTURE_FLIPBOOKTEST, -1, MAT_LIGHTING | MAT_FOG | MAT_DEPTH_READ | MAT_CI, CC_DECAL_SHADE_PRIM, COLFLAG_GRIP(8), FLOORDEC_NONE, 0, 0, 0, 0, 0, 0, 0, 0}, // flipbooktest
};