#pragma once

#include "global.h"

#include "../src/assets.h"

const TextureInfo gTextureIDs[] = {
    {"grass0.i4", TEX_NULL, 0, 0},
    {"health.ia4", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"plant1.ia8", TEX_CLAMP_V | TEX_MIRROR_H, 0, 0},
    {"shadow.i4", TEX_MIRROR_H | TEX_MIRROR_V, 0, 0},
    {"stone.ci4", TEX_NULL, 0, 0},
    {"water.i4", TEX_NULL, 0, 0},
    {"kitchentile.i8", TEX_NULL, 0, 0},
    {"introsign.i4", TEX_NULL, 0, 0},
    {"introsign2.i4", TEX_NULL, 0, 0},
    {"eye1.ia4", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"eyebrow1.ia4", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"mouth1.ia4", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"shirt.ci8", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"trousers.ci8", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"rocksurface4.ci4", TEX_NULL, 0, 0},
    {"mountainsidebottom.ci4", TEX_NULL, 0, 0},
    {"skybox1.ci8", TEX_NULL, 0, 0},
    {"logwall.i8", TEX_NULL, 0, 0},
    {"railing.ia4", TEX_CLAMP_V, 0, 0},
    {"crate.i8", TEX_MIRROR_H | TEX_MIRROR_V, 0, 0},
    {"grass1.i4", TEX_NULL, 0, 0},
    {"body1.i8", TEX_CLAMP_V | TEX_MIRROR_H, 0, 0},
    {"eye1_b.ia4", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"flipbooktest.ci8", TEX_NULL, 31, 1},
    {"rockside3.i4", TEX_NULL, 0, 0},
    {"rockside4.i4", TEX_NULL, 0, 0},
    {"envmap.i8", TEX_CLAMP_H | TEX_CLAMP_V, 0, 0},
    {"dust_clouds.i8", TEX_NULL, 0, 0},
    {"dust_mat0.ci8", TEX_NULL, 0, 0},
    {"dust_mat1.ci8", TEX_NULL, 0, 0},
    {"dust_mat2.ci4", TEX_NULL, 0, 0},
    {"dust_mat3.ci4", TEX_NULL, 0, 0},
    {"dust_mat5.ci4", TEX_NULL, 0, 0},
    {"dust_mat6.ci4", TEX_NULL, 0, 0},
    {"dust_mat7.ci4", TEX_NULL, 0, 0},
    {"dust_mat8.ci4", TEX_NULL, 0, 0},
    {"dust_mat9.ci8", TEX_NULL, 0, 0},
    {"dust_mat10.ci8", TEX_NULL, 0, 0},
    {"dust_mat11.ci4", TEX_NULL, 0, 0},
    {"dust_mat12.i4", TEX_NULL, 0, 0},
    {"dust_mat13.ci4", TEX_NULL, 0, 0},
    {"dust_mat14.ci8", TEX_NULL, 0, 0},
    {"dust_mat15.ci8", TEX_NULL, 0, 0},
    {"dust_mat16.ci4", TEX_NULL, 0, 0},
    {"dust_mat17.ci4", TEX_NULL, 0, 0},
    {"dust_mat18.ci4", TEX_NULL, 0, 0},
    {"dust_mat19.i8", TEX_NULL, 0, 0},
    {"dust_mat20.ci8", TEX_NULL, 0, 0},
    {"dust_mat21.ci8", TEX_NULL, 0, 0},
    {"dust_mat22.ci8", TEX_NULL, 0, 0},
    {"dust_mat23.ci8", TEX_NULL, 0, 0},
    {"dust_mat24.ci4", TEX_NULL, 0, 0},
    {"dust_mat25.i8", TEX_NULL, 0, 0},
    {"dust_mat26.ci8", TEX_NULL, 0, 0},
    {"dust_mat27.ci8", TEX_NULL, 0, 0},
    {"dust_mat28.ci8", TEX_NULL, 0, 0},
    {"dust_mat29.ci8", TEX_NULL, 0, 0},
    {"dust_mat30.ci4", TEX_NULL, 0, 0},
    {"dust_mat31.ci4", TEX_NULL, 0, 0},
    {"dust_mat32.ci4", TEX_NULL, 0, 0},
    {"dust_mat33.ci4", TEX_NULL, 0, 0},
};